services:
  - type: web
    name: tp2-pollution
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist/TP2/browser
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /*
        destination: /index.html