services:
  - type: web
    name: tp02-pollution
    env: static
    buildCommand: npm ci && npm run build --configuration=production
    staticPublishPath: dist/tp02-pollution/browser
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /*
        destination: /index.html